clc;
clear all;
close all;
k=0.8;
w=pi/128;
q=pi/6;
load golomb1
M=length(x);
ts=0.00001;
t=(0:M-1)*ts;
subplot(4,1,1);
plot(x);
title('GOLOMB SIGNAL');
ylabel('amp');
xlabel('samples');
y=hilbert(x);
env=abs(y);
ph=angle(y);
subplot(4,1,2);
plot(env);
title('ENVELOPE');
ylabel('amp');
xlabel('samples');
subplot(4,1,3);
plot(ph);
title('PHASE');
ylabel('phase');
xlabel('samples');
phu=unwrap(ph);
subplot(4,1,4);
plot(phu);
title('UNWRAPPED PHASE');
ylabel('phase');
xlabel('samples');